### ISSUE TITLE
RestClient::ResourceNotFound - 404 Resource Not Found:

### ISSUE THREAD

**Issue by henryserrano1978** [sirhopcount/tayu#4]
Hello, I'm getting the following error. Any help would be greatly appreciated:

[2015-06-04 20:11:09] INFO  WEBrick::HTTPServer#start: pid=2628 port=8144
2015-06-04 20:12:05 - RestClient::ResourceNotFound - 404 Resource Not Found:
    /usr/lib/ruby/vendor_ruby/restclient/abstract_response.rb:48:in `return!'
    /usr/lib/ruby/vendor_ruby/restclient/request.rb:230:in`process_result'
    /usr/lib/ruby/vendor_ruby/restclient/request.rb:178:in `block in transmit'
    /usr/lib/ruby/1.9.1/net/http.rb:746:in`start'
    /usr/lib/ruby/vendor_ruby/restclient/request.rb:172:in `transmit'
    /usr/lib/ruby/vendor_ruby/restclient/request.rb:64:in`execute'
    /usr/lib/ruby/vendor_ruby/restclient/request.rb:33:in `execute'
    /usr/lib/ruby/vendor_ruby/restclient.rb:68:in`get'
    /var/lib/gems/1.9.1/gems/tayu-0.0.3/lib/tayu.rb:45:in `get_nodes'
    /var/lib/gems/1.9.1/gems/tayu-0.0.3/lib/tayu.rb:69:in`generate_body'
    /var/lib/gems/1.9.1/gems/tayu-0.0.3/lib/tayu.rb:109:in `block in <class:Tayu>'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in`call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`[]'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in`route_eval'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in`block in process_route'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in`process_route'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in`each'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in`block in dispatch!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`catch'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in`dispatch!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`block in invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in`call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in`call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in`call'
    /var/lib/gems/1.9.1/gems/rack-1.6.1/lib/rack/nulllogger.rb:9:in `call'
    /var/lib/gems/1.9.1/gems/rack-1.6.1/lib/rack/head.rb:13:in`call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in`call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`block in call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`call'
    /var/lib/gems/1.9.1/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
    /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
    /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
    /usr/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'
localhost - - [04/Jun/2015:20:12:05 PDT] "GET / HTTP/1.1" 500 4110

**Comment by sirhopcount** [comment]
Hi,

There really hasn't been any active development going on for this project (seeing I am not using it myself anymore). I see that your using ruby 1.9.1 and I haven't tested if it works in "newer" version than 1.8.4.

You could try and run it via rbenv of rvm with ruby version 1.8.4 but I don't know if that really a wise thing to do. 

Luckily there are some alternatives who are still being actively developed on the rundeck plugin page:

http://rundeck.org/plugins/index.html

It might not be the the answer you where looking for but I hope it helps.
